### ISSUE TITLE
Handle the `origin-trials` header

### ISSUE THREAD

**Issue by slightlyoff** [beaufortfrancois/origin-trials-chrome-extension#1]
This extension is awesome! Would it be possible to use [`declarativeWebRequest`](https://developer.chrome.com/extensions/declarativeWebRequest) to look for the `origin-trial` respons header? It'd allow us to see this light up for experiments like [Navigation Preload](https://developers.google.com/web/updates/2017/02/navigation-preload).

**Comment by beaufortfrancois** [comment]
I've just published an update that includes checking for the `Origin-Trial` response header.
See https://github.com/beaufortfrancois/origin-trials-chrome-extension/commit/044e18c0b3089f26f35c976997013c6acbbb5dbc

You can try it by going to https://horo-test.appspot.com/navigationpreload/demo/ and checking that the extension icon shows up.
